# Generated by Django 5.0.6 on 2024-06-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_board',
            new_name='is_staff',
        ),
    ]
