# Generated by Django 5.0.6 on 2024-06-28 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('number', models.CharField(primary_key=True, serialize=False)),
                ('balance', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Ділянка',
                'verbose_name_plural': 'Ділянки',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('value_day', models.IntegerField(verbose_name='День')),
                ('value_night', models.IntegerField(blank=True, null=True, verbose_name='Ніч')),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Показ надав')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='electricity.plot')),
            ],
            options={
                'verbose_name': 'Показ',
                'verbose_name_plural': 'Покази',
            },
        ),
    ]
