# Generated by Django 5.0.6 on 2024-06-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='plot',
            field=models.CharField(default='', verbose_name='Ділянка'),
        ),
    ]
