# Generated by Django 5.0.6 on 2024-07-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='measurement',
            name='comment',
            field=models.CharField(blank=True, default='', null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='plot',
            name='value_day_avg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='value_night_avg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='verbose',
            field=models.CharField(default='', max_length=5),
        ),
    ]
