# Generated by Django 5.0.6 on 2024-06-23 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='person',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
