# Generated by Django 5.0.6 on 2024-06-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0002_alter_measurement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
    ]
