# Generated by Django 5.0.6 on 2024-06-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0003_alter_measurement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='value_day',
            field=models.IntegerField(verbose_name='Денний тариф'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='value_night',
            field=models.IntegerField(verbose_name='Нічний тариф'),
        ),
    ]
