# Generated by Django 5.0.6 on 2024-07-07 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0004_rename_is_paid_measurement_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_measurements', to=settings.AUTH_USER_MODEL, verbose_name='Оплату підтвердив'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='comment',
            field=models.CharField(blank=True, default='', null=True, verbose_name='Коментар (опціонально)'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата підтвердження'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Поточний баланс'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='value_day_avg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Середньомісячний показ "День"'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='value_night_avg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Середньомісячний показ "Ніч"'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='verbose',
            field=models.CharField(default='', max_length=5, verbose_name='Номер ділянки'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
    ]
