# Generated by Django 5.0.6 on 2024-06-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0004_alter_measurement_value_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='month',
            field=models.IntegerField(default=1, verbose_name='Місяць'),
        ),
    ]
