# Generated by Django 5.0.6 on 2024-06-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0005_measurement_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='year',
            field=models.IntegerField(default=2024, verbose_name='Рік'),
        ),
    ]
