# Generated by Django 5.0.6 on 2024-07-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0006_alter_measurement_value_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='value_day',
            field=models.IntegerField(default=0, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='value_night',
            field=models.IntegerField(default=0, verbose_name='Ніч'),
        ),
    ]
