# Generated by Django 5.0.6 on 2024-06-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0006_remove_electricitymeasurement_measurement_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElectricityMeasurement',
            new_name='Measurement',
        ),
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(default='', max_length=50, verbose_name='Юзернейм'),
            preserve_default=False,
        ),
    ]
