# Generated by Django 5.0.6 on 2024-06-25 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0006_measurement_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='month',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='year',
        ),
    ]
